name: Auto Scheduled Bot

on:
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Execute Python script
        env:
          MY_COOKIE: ${{ secrets.MY_COOKIE }}
          SHEET_URL: ${{ secrets.SHEET_URL }}
        run: python main.py
