name: Auto Extract SPX Cookie

on:
  schedule:
    - cron: '13 18 * * *' # Kích hoạt lúc ~01:13 sáng (Giờ VN)
    - cron: '37 21 * * *' # Kích hoạt lúc ~04:37 sáng (Giờ VN)
    - cron: '04 0 * * *'  # Kích hoạt lúc ~07:04 sáng (Giờ VN)
    - cron: '52 3 * * *'  # Kích hoạt lúc ~10:52 sáng (Giờ VN)
    - cron: '23 6 * * *'  # Kích hoạt lúc ~13:23 chiều (Giờ VN)
    - cron: '48 9 * * *'  # Kích hoạt lúc ~16:48 chiều (Giờ VN)
    - cron: '19 12 * * *' # Kích hoạt lúc ~19:19 tối (Giờ VN)
    - cron: '57 15 * * *' # Kích hoạt lúc ~22:57 tối (Giờ VN)
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Python dependencies & Playwright Browser
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          playwright install chromium --with-deps

      - name: Execute Python script (Auto Retry on Failure)
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 10
          max_attempts: 3
          retry_wait_seconds: 180
          command: python main.py
        env:
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
          SHEET_URL: ${{ secrets.SHEET_URL }}
